---
- hosts: node_vms
  become: yes # Run as root
  vars_files:
    - secrets.yml # Load encrypted password
  tasks:
    - name: Create user 'vm'
      ansible.builtin.user:
        name: vm
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Ensure user is in sudo group
      ansible.builtin.user:
        name: vm
        groups: sudo
        append: yes

    - name: Set up SSH key for vm user
      ansible.builtin.authorized_key:
        user: vm
        key: "{{ lookup('file', '~/.ssh/lab_nodes_id_ed25519.pub') }}"
        state: present

    - name: Ensure vm user has passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/vm
        line: 'vm ALL=(ALL) NOPASSWD: ALL'
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'
    - name: Add VM host keys to known_hosts
      ansible.builtin.known_hosts:
        name: '{{ ansible_host }}'
        key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 ' + ansible_host) }}"
        state: present
